// AUTO-GENERATED by typescript-type-def

export type I64=number;
export type F32=number;
export type ExpenseSchema=("EqualAll"|{"EqualPersons":(I64)[];}|"PayerOnly");
export type AddExpenseRequest={"group_person_id":I64;"creator_id":I64;"amount":F32;"schema":ExpenseSchema;};
export type NewGroupPersonAlias=({"User":{"user_id":I64;};}|{"NonUser":{"name":string;};});
export type AddGroupPersonRequest={"creator_id":I64;"group_id":I64;"alias":NewGroupPersonAlias;};
export type AddGroupRequest={"user_id":I64;"name":string;};
export type AddUserRequest={"email":string;"handle":string;"password":string;"name":string;};
export type Expense={"id":I64;"amount":F32;};
export type Group={"id":I64;"name":string;};
export type GroupPerson={"id":I64;"name":string;};
export type TrustUsersRequest={"source_id":I64;"target_id":I64;};
export type User={"id":I64;"email":string;"handle":string;"name":string;};
